import { LiaHomeSolid } from "react-icons/lia"
import { TbTriangleSquareCircle } from "react-icons/tb"
import { FaRegUser } from "react-icons/fa6"
import { AiOutlineDollarCircle } from "react-icons/ai"
import { IoIosNotificationsOutline } from "react-icons/io"
import { AiOutlineContacts } from "react-icons/ai"